apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ambassador-monitor
  labels:
    app: emissary-ingress
spec:
  namespaceSelector:
    matchNames:
    - emissary-ingress
  selector:
    matchLabels:
      service: ambassador-admin
  endpoints:
  - port: ambassador-admin
