apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: grafana-mapping
  namespace: monitoring
  labels:
    app.kubernetes.io/component: emissary-ingress
    app.kubernetes.io/managed-by: sharmio
    app.kubernetes.io/name: grafana-mapping
  annotations:
    a8r.io/bugs: https://github.com/Sharmio/infra-public/issues
    a8r.io/dependencies: emissary-ingress
    a8r.io/description: This mapping will defines how incoming HTTP requests should be routed to the appropriate backend services i.e. grafana service within a Kubernetes cluster.
    a8r.io/documentation: https://github.com/Sharmio/infra-public/tree/main/aws/grafana-via-emissary
    a8r.io/owner: Sharmio
    a8r.io/repository: https://github.com/Sharmio/infra-public/
    meta.helm.sh/release-name: grafana-mapping
    meta.helm.sh/release-namespace: monitoring
spec:
  prefix: /grafana
  service: grafana-stack
  ambassador_id:
  - 'emissary'
  hostname: your-domain
